name: shfmt
base: core22
version: "3.12.0"
# https://github.com/snapcore/snapd/blob/master/spdx/licenses.go
license: "BSD-3-Clause"
summary: A shell parser, formatter and interpreter (POSIX/Bash/mksh).
description: |
  "A shell parser, formatter and interpreter (POSIX/Bash/mksh)."

confinement: strict
grade: stable
architectures:
  - build-on: amd64

plugs:
  dot-editorconfig:
    interface: personal-files
    read:
      - $HOME/.editorconfig

parts:
  shfmt:
    # Use the nil plugin with wget until bz2 is supported by snapcraft.
    plugin: nil
    build-packages:
      - wget
    override-pull: |
      wget https://github.com/mvdan/sh/releases/download/v$(craftctl get version)/$CRAFT_PROJECT_NAME_v$(craftctl get version)_linux_$CRAFT_ARCH_BUILD_FOR
    override-build: |
      craftctl default
      install $CRAFT_PROJECT_NAME_v$(craftctl get version)_linux_$CRAFT_ARCH_BUILD_FOR $CRAFT_PART_INSTALL/shfmt

apps:
  shfmt:
    command: shfmt
    plugs:
      - home
      - network
      - dot-editorconfig
